server:
  port: 8000

spring:
  datasource:
    url: jdbc:h2:file:~/data/demo;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: create-drop